name: Python Unit, Integration, and Regression Tests

on:
  push:
    branches:
      - '*' # Trigger on all branches
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit tests
      run: |
        python -m unittest discover -s tests/unit -p '*test_*.py'

    - name: Run integration tests
      run: |
        python -m unittest discover -s tests/integration -p '*test_*.py'

    - name: Run regression tests
      run: |
        python -m unittest discover -s tests/regression -p '*test_*.py'

    # Add steps for merging and deploying
    - name: Merge branch into main
      if: github.ref != 'refs/heads/main' # Only merge if not on main branch
      run: |
        git checkout main
        git merge $GITHUB_REF
        git push

    - name: Deploy project
      if: github.ref == 'refs/heads/main' # Only deploy if on main branch
      # Add your deployment steps here
